/*
  3474. Lexicographically Smallest Generated String
  
  You are given two strings, str1 and str2, of lengths n and m, respectively.
  A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
      If str1[i] == 'T', the of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
      If str1[i] == 'F', the of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
  
  Return the possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
  
  Example 1:
  Input: str1 = "TFTF", str2 = "ab"
  Output: "ababa"
  Explanation:
  The table below represents the string "ababa"
  Index	T/F	Substring of length m  
  The strings "ababa" and "ababb" can be generated by str1 and str2.
  Return "ababa" since it is the lexicographically smaller string.
  
  Example 2:
  Input: str1 = "TFTF", str2 = "abc"
  Output: ""
  Explanation:
  No string that satisfies the conditions can be generated.
  
  Example 3:
  Input: str1 = "F", str2 = "d"
  Output: "a"
*/
public class Solution {
    public string GenerateString(string str1, string str2) {
        int n = str1.Length;
        int m = str2.Length;

        int total = n + m - 1;

        Span<char> res = total > 256 
            ? new char[total] : stackalloc char[total];
        Span<bool> fx = total > 256 
            ? new bool[total] : stackalloc bool[total];

        res.Fill('a');

        for (int i = 0; i < n; ++i) {
            char ch = str1[i];
            if (ch != 'T')
                continue;

            for (int j = 0; j < m; ++j) {
                int k = i + j;
                if (fx[k] && res[k] != str2[j])
                    return "";

                res[k] = str2[j];
                fx[k] = true;
            }
        }

        for (int i = 0; i < n; ++i) {
            char ch = str1[i];
            if (ch != 'F')
                continue;

            bool matched = true;
            for (int j = 0; j < m; ++j)
                if (res[i + j] != str2[j]) {
                    matched = false;
                    break;
                }

            if (!matched)
                continue;

            int pos = -1;
            for (int k = i + m - 1; k >= i; --k) {
                if (!fx[k]) {
                    pos = k;
                    break;
                }
            }

            if (pos == -1)
                return "";

            res[pos] = 'b';
        }

        return new string(res);
    }
}
