/*
  3474. Lexicographically Smallest Generated String
  
  You are given two strings, str1 and str2, of lengths n and m, respectively.
  A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
      If str1[i] == 'T', the of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
      If str1[i] == 'F', the of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
  
  Return the possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
  
  Example 1:
  Input: str1 = "TFTF", str2 = "ab"
  Output: "ababa"
  Explanation:
  The table below represents the string "ababa"
  Index	T/F	Substring of length m  
  The strings "ababa" and "ababb" can be generated by str1 and str2.
  Return "ababa" since it is the lexicographically smaller string.
  
  Example 2:
  Input: str1 = "TFTF", str2 = "abc"
  Output: ""
  Explanation:
  No string that satisfies the conditions can be generated.
  
  Example 3:
  Input: str1 = "F", str2 = "d"
  Output: "a"
*/
impl Solution {
    pub fn generate_string(str1: String, str2: String) -> String {
        let s = str1.into_bytes();
        let t = str2.into_bytes();
        let (n, m) = (s.len(), t.len());
        let total = n + m - 1;
        
        let mut ans = vec![b'a'; total];
        let mut fixed = vec![false; total];
        
        for i in 0..n {
            if s[i] != b'T' { 
                continue;
            }
            for j in 0..m {
                let k = i + j;
                if fixed[k] && ans[k] != t[j] {
                    return String::new();
                }
                ans[k] = t[j];
                fixed[k] = true;
            }
        }
        
        for i in 0..n {
            if s[i] != b'F' { 
                continue;
            }

            let matches = (0..m).all(|j| ans[i + j] == t[j]);
            if !matches { 
                continue;
            }
            
            let pos = (i..i + m).rev().find(|&k| !fixed[k]);
            match pos {
                Some(k) => ans[k] = b'b',
                None => return String::new(),
            }
        }
        
        String::from_utf8(ans).unwrap()
    }
}
